### PR TITLE
Continuation of new fluent interfaces and components

### PR DESCRIPTION
**Pull request by stefan-freude**

### CODE REVIEW

**Comment by mstahv** [comment]
Lot of good stuff here, I'll look into this!

**Comment by mstahv** [comment]
Could you rebase the changes on the master branch?

@mmerruko we also need to do the tabs-vs-spaces decision ;-) I'd go with spaces (IntelliJ defaults).

**Comment by stefan-freude** [comment]
I rebased the project and used spaces (as default).
I don't know, why github has conflicts in VTextField.java, 
I added FluentHasStyle, withId an rearranged imports.

**Comment by mstahv** [comment]
Thanks Stefan, your first code contribution is in, keep them coming!

**Comment by mstahv** [comment]
@mmerruko & @stefan-freude project now has formatter plugin configured. You can issue it by executing mvn formatter:format , which should do pretty much the same as default eclipse settings.

**Pull request merged**
