### PR TITLE
Latest

### PR DESCRIPTION
**Pull request by melistik**
i've created a **latest** branch without module separation and some fixes and improvements

### CODE REVIEW

**Comment by mstahv** [comment]
Thanks! 

I hope I did the manual rebase correctly.

**Comment by mstahv** [comment]
I think VEmphasis didn't compile for some reason, removed fluent click notifier

**Comment by melistik** [comment]
didn't you wanted to have it on a separate branch? I'm a bit surprised...

**Comment by mstahv** [comment]
I would suggest all users currently to use V13 instead of V10 which lacks a lot of very essential features. If there appears a need for V10 compatible version, we can create that branch later from a change before this change.

**Pull request merged**
